name: Brave IDE

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag and set next tag
        id: version
        run: |
          # Get the latest tag matching v1.*
          latest_tag=$(git tag --list "v1.*" --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            next_tag="v1.0.0"
          else
            # Extract the version numbers
            IFS='.' read -r major minor patch <<<"${latest_tag#v}"
            patch=$((patch + 1))
            next_tag="v${major}.${minor}.${patch}"
          fi
          echo "Next tag: $next_tag"
          echo "TAG_NAME=$next_tag" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push Git tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Download Brave Installer
        run: |
          curl -L -o BraveBrowserSetup.exe \
          https://referrals.brave.com/latest/BraveBrowserSetup.exe

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: BraveBrowserSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
